on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
name: k6 Load Test
jobs:
  k6_ubuntu_load_test:
    name: k6 Ubuntu Load Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: script.js          
